'use strict';
(()=>{
 const store=window.bettaApp.store,C=BettaStore.decorCatalog;
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const button=(text,run,id)=>{const b=el('button',text,'secondary');b.type='button';b.onclick=run;if(id)b.id=id;return b;};
 const dialog=el('dialog',undefined,'decor-dialog');dialog.id='decor-panel';dialog.setAttribute('aria-labelledby','decor-title');
 const header=el('header'),title=el('h2','Arreda il tuo acquario');title.id='decor-title';header.append(title,button('Chiudi',()=>dialog.close()));
 const tabs=el('nav'),body=el('div',undefined,'decor-content'),notice=el('p','','decor-notice');notice.setAttribute('role','status');
 const view=button('Vista 3D',()=>{dialog.classList.toggle('decor-compact');view.textContent=dialog.classList.contains('decor-compact')?'Mostra controlli':'Vista 3D';},'decor-3d-view');header.append(view);for(const [value,label] of [['translate','Sposta'],['rotate','Ruota']]){const tool=button(label,()=>{transformMode=value;draw();},'decor-compact-'+value);tool.classList.add('decor-compact-tool');header.append(tool);}dialog.append(header,tabs,notice,body);document.body.append(dialog);
 let mode='editor',key=null,draft=null,selected=null,selectedBase=null,map=null,markers=null,summary=null,transformMode='translate';
 const clone=x=>JSON.parse(JSON.stringify(x));
 const preview=()=>document.dispatchEvent(new CustomEvent('aquarium-decor-preview',{detail:key&&draft?{key,layout:clone(draft),editing:dialog.open&&mode==='editor',transformMode,selected:selectedBase||(selected===null?null:'item:'+selected)}:null}));
 const available=(d,s=store.getState())=>s.mode==='creative'||s.decorOwned.includes(d.id);
 const attempt=fn=>{try{fn();notice.textContent='';}catch(e){notice.textContent=e.message;}};
 function tankOptions(s){const h=BettaStore.housing(s);return [h.community,...h.breeders,...h.nursery,...(s.mode==='career'?Array.from({length:s.career.shopSlots},(_,i)=>({key:'shop-'+i,name:'Vetrina '+(i+1),unlocked:true})):[])].filter(t=>t.unlocked!==false);}
 function loadTank(next){key=next;draft=clone(store.getState().tankDecor?.[key]||{base:true,items:[]});selectedBase=null;selected=draft.items[0]?.id??null;window.betta3d?.focusDecorTank(key);preview();draw();}
 function refreshMap(){if(!markers)return;markers.replaceChildren();for(const item of draft.items){const d=C.find(d=>d.id===item.type),b=button(d.category==='Piante'?'♣':d.category==='Sassi'?'◆':'⌁',()=>{selectedBase=null;selected=item.id;draw();});b.className='decor-marker';b.dataset.item=item.id;b.setAttribute('aria-label',d.name+' '+item.id);b.setAttribute('aria-pressed',String(item.id===selected));b.style.left=(50+item.x/2.4*100)+'%';b.style.top=(50+item.z/1.0*100)+'%';b.style.transform='translate(-50%,-50%) rotate('+item.angle+'rad) scale('+item.scale+')';markers.append(b);}
  if(summary)summary.textContent=draft.items.length+' / 16 decorazioni aggiunte';
 }
 function update(){preview();refreshMap();}
 function range(label,id,min,max,step,value,change){const row=el('label',label),input=el('input');input.type='range';input.id=id;input.min=min;input.max=max;input.step=step;input.value=value;input.oninput=()=>{change(Number(input.value));update();};row.append(input);return row;}
 function draw(){
  for(const value of ['translate','rotate'])document.getElementById('decor-compact-'+value)?.setAttribute('aria-pressed',String(transformMode===value));preview();const s=store.getState();tabs.replaceChildren(button('Allestimento',()=>{mode='editor';if(!key)loadTank(tankOptions(s)[0].key);else draw();},'decor-editor-tab'),button(s.mode==='career'?'Negozio decorazioni':'Catalogo completo',()=>{mode='shop';draw();},'decor-shop-tab'));
  for(const [i,b] of [...tabs.children].entries())b.setAttribute('aria-pressed',String(mode===(i?'shop':'editor')));
  body.replaceChildren();map=null;markers=null;
  if(mode==='shop'){
   body.append(el('p',s.mode==='career'?s.career.cash+' monete · Ogni acquisto sblocca il tipo per sempre, in tutti gli acquari.':'Tutte le decorazioni sono già disponibili gratuitamente.'));
   for(const category of ['Piante','Sassi','Radici']){body.append(el('h3',category));const grid=el('div',undefined,'decor-catalog');for(const d of C.filter(d=>d.category===category)){const card=el('article');card.dataset.decor=d.id;card.append(el('strong',d.name),el('small',available(d,s)?'Disponibile':d.price+' monete'));const b=button(available(d,s)?'Sbloccato':'Acquista',()=>attempt(()=>{store.buyDecoration(d.id);draw();}), 'decor-buy-'+d.id);b.disabled=available(d,s)||s.career?.cash<d.price;card.append(b);grid.append(card);}body.append(grid);}return;
  }
  const options=tankOptions(s);if(!key||!options.some(t=>t.key===key)){if(!options.length)return;key=options[0].key;draft=clone(s.tankDecor?.[key]||{base:true,items:[]});}
  const select=el('select');select.id='decor-tank';select.setAttribute('aria-label','Acquario da arredare');for(const t of options){const o=el('option','#'+BettaStore.tankNumber(t.key)+' · '+(s.tankNames?.[t.key]||t.name));o.value=t.key;select.append(o);}select.value=key;select.onchange=()=>loadTank(select.value);body.append(select);const tools=el('div',undefined,'decor-actions');for(const [value,label] of [['translate','Sposta lungo gli assi'],['rotate','Ruota']]){const tool=button(label,()=>{transformMode=value;draw();},'decor-tool-'+value);tool.setAttribute('aria-pressed',String(transformMode===value));tools.append(tool);}body.append(tools,el('p','Trascina le frecce colorate per spostare lungo un asse. Usa l’anello per ruotare. W: sposta · E: ruota.','view-note'));
  const base=el('label',undefined,'decor-base'),check=el('input');check.type='checkbox';check.id='decor-base';check.checked=draft.base;check.onchange=()=>{draft.base=check.checked;update();};base.append(check,document.createTextNode('Conserva l’arredamento iniziale'));body.append(base,button('Rigenera casualmente',()=>{draft.base=true;draft.baseSeed=Math.floor(Math.random()*4294967296);delete draft.baseMoves;selectedBase=null;for(const item of draft.items){item.seed=Math.floor(Math.random()*4294967296);item.x=(Math.random()-.5)*1.9;item.z=-.35+Math.random()*.65;item.angle=(Math.random()-.5)*Math.PI*2;}update();draw();},'decor-randomize'));
  body.append(el('p','Nella vista 3D, clicca una pianta, un sasso o una radice e trascinala per spostarla. Puoi muovere anche l’arredamento iniziale.','view-note'));
  body.append(el('p','Pianta della vasca: tocca un elemento per selezionarlo e trascinalo per spostarlo. Usa i cursori per una posizione precisa.','view-note'));
  map=el('div',undefined,'decor-map');map.id='decor-map';map.setAttribute('aria-label','Pianta dell’acquario');map.append(el('span','FONDO'),el('small','VETRO FRONTALE'));markers=el('div',undefined,'decor-markers');map.append(markers);body.append(map);
  let drag=null;
  map.onpointerdown=e=>{const hit=e.target.closest('[data-item]');if(!hit)return;selectedBase=null;selected=Number(hit.dataset.item);drag=selected;map.setPointerCapture(e.pointerId);e.preventDefault();refreshMap();};
  map.onpointermove=e=>{if(drag===null)return;const item=draft.items.find(i=>i.id===drag),bounds=map.getBoundingClientRect();item.x=Math.max(-1.02,Math.min(1.02,((e.clientX-bounds.left)/bounds.width-.5)*2.4));item.z=Math.max(-.4,Math.min(.4,((e.clientY-bounds.top)/bounds.height-.5)));update();};
  map.onpointerup=()=>{if(drag!==null){drag=null;draw();}};map.onpointercancel=()=>{drag=null;draw();};
  summary=el('p','','view-note');body.append(summary);refreshMap();
  if(draft.items.length){const elements=el('select');elements.id='decor-element';elements.setAttribute('aria-label','Elemento da modificare');const empty=el('option','Seleziona un elemento');empty.value='';elements.append(empty);for(const item of draft.items){const option=el('option',C.find(d=>d.id===item.type).name+' · '+item.id);option.value=item.id;elements.append(option);}elements.value=selected??'';elements.onchange=()=>{selectedBase=null;selected=Number(elements.value)||null;draw();};body.append(elements);}
  if(selectedBase)body.append(el('p','Arredamento iniziale selezionato: trascinalo nella vista 3D.','view-note'));
  const chosen=draft.items.find(i=>i.id===selected);
  if(chosen){const controls=el('section',undefined,'decor-controls');controls.append(el('h3',C.find(d=>d.id===chosen.type).name),range('Sinistra / destra','decor-x',-1.02,1.02,.01,chosen.x,v=>chosen.x=v),range('Fondo / fronte','decor-z',-.4,.4,.01,chosen.z,v=>chosen.z=v),range('Altezza','decor-lift',-1.2,1.2,.01,chosen.lift||0,v=>chosen.lift=v),range('Dimensione','decor-scale',.5,1.4,.05,chosen.scale,v=>chosen.scale=v),range('Rotazione','decor-angle',-Math.PI,Math.PI,.05,chosen.angle,v=>chosen.angle=v),button('Nuova forma',()=>{chosen.seed=Math.floor(Math.random()*4294967295);update();},'decor-variation'),button('Rimuovi',()=>{draft.items=draft.items.filter(i=>i.id!==selected);selected=null;update();draw();},'decor-remove'));body.append(controls);}
  const add=el('div',undefined,'decor-add'),picker=el('select');picker.id='decor-type';picker.setAttribute('aria-label','Decorazione da aggiungere');
  for(const d of C.filter(d=>available(d,s))){const option=el('option',d.name);option.value=d.id;picker.append(option);}
  const addButton=button('Aggiungi',()=>{if(draft.items.length>=16){notice.textContent='Puoi aggiungere fino a 16 elementi per vasca.';return;}const item={id:Math.max(0,...draft.items.map(i=>i.id))+1,type:picker.value,x:0,z:-.2,scale:1,angle:0,seed:Math.floor(Math.random()*4294967295)};draft.items.push(item);selectedBase=null;selected=item.id;update();draw();},'decor-add');addButton.disabled=!picker.options.length||draft.items.length>=16;add.append(picker,addButton);body.append(add);
  if(!picker.options.length)body.append(el('p','Acquista la tua prima decorazione nel negozio. Puoi conservare o rimuovere l’allestimento iniziale.'));
  const footer=el('div',undefined,'decor-actions');footer.append(button('Salva allestimento',()=>attempt(()=>{store.setTankDecor(key,draft);notice.textContent='Allestimento salvato.';window.bettaApp.message('Allestimento salvato per l’acquario #'+BettaStore.tankNumber(key));dialog.close();}),'decor-save'),button('Ripristina iniziale',()=>{draft={base:true,items:[]};selected=null;selectedBase=null;update();draw();},'decor-reset'),button('Annulla',()=>dialog.close(),'decor-cancel'));body.append(footer);
 }
 dialog.addEventListener('contextmenu',event=>{if(mode==='editor'){event.preventDefault();selected=null;selectedBase=null;draw();}});
 dialog.addEventListener('close',()=>{key=null;draft=null;selected=null;selectedBase=null;preview();});
 document.addEventListener('keydown',event=>{if(event.key==='Escape'&&dialog.open)dialog.close();});
 document.addEventListener('keydown',event=>{if(!dialog.open||mode!=='editor'||event.ctrlKey||event.metaKey||event.altKey||event.target.closest?.('input,select,textarea,[contenteditable=true]'))return;const value={w:'translate',e:'rotate'}[event.key.toLowerCase()];if(value){event.preventDefault();event.stopImmediatePropagation();transformMode=value;draw();}},true);
 store.subscribe(()=>{if(dialog.open&&mode==='shop')draw();});
 document.addEventListener('aquarium-decor-edit',event=>{const e=event.detail;if(!dialog.open||mode!=='editor'||e.tank!==key||!draft)return;if(e.object===null){selected=null;selectedBase=null;draw();return;}selectedBase=e.object.startsWith('base:')?e.object:null;selected=selectedBase?null:Number(e.object.slice(5));if(e.position){if(selectedBase){draft.baseMoves??=[];let move=draft.baseMoves.find(m=>m.key===selectedBase);if(!move){move={key:selectedBase,x:0,z:0};draft.baseMoves.push(move);}Object.assign(move,e.position);}else {const item=draft.items.find(i=>i.id===selected);if(!item)return;Object.assign(item,e.position);}update();for(const [id,value] of [['decor-x',e.position.x],['decor-z',e.position.z],['decor-lift',e.position.lift],['decor-angle',e.position.angle]]){const input=document.getElementById(id);if(input&&value!==undefined)input.value=value;}}if(!e.position||e.end)draw();});
 window.BettaDecorUI={open(next=null){mode='editor';notice.textContent='';if(!dialog.open)dialog.show();dialog.classList.remove('decor-compact');view.textContent='Vista 3D';loadTank(next||tankOptions(store.getState())[0].key);},openShop(){mode='shop';notice.textContent='';if(!dialog.open)dialog.show();draw();}};
})();
